import { NextResponse } from "next/server";

import { Product } from "@/types";

export const products: Product[] = [
  {
    id: 1,
    title: "NVIDIA RTX 5090",
    slug: "nvidia-rtx-5090",
    description: "32 Go GDDR7 – Carte graphique ultime de nouvelle génération, pour des performances inégalées en 8K et au-delà.",
    price: 2499,
    imageUrl: "/assets/5000-gen/rtx-5090.webp",
    inStock: false,
  },
  {
    id: 3,
    title: "NVIDIA RTX 5080",
    slug: "nvidia-rtx-5080",
    description: "20 Go GDDR7 – Puissance nouvelle génération pour un gaming fluide et immersif en 4K.",
    price: 1599,
    imageUrl: "/assets/5000-gen/rtx-5080.webp",
    inStock: false,
  },
  {
    id: 4,
    title: "NVIDIA RTX 5070 Ti",
    slug: "nvidia-rtx-5070-ti",
    description: "16 Go GDDR7 – L'équilibre parfait entre performances de pointe et prix attractif.",
    price: 999,
    imageUrl: "/assets/5000-gen/rtx-5070-ti.jpg",
    inStock: false,
  },
  {
    id: 5,
    title: "NVIDIA RTX 5070",
    slug: "nvidia-rtx-5070",
    description: "16 Go GDDR7 – Profitez du gaming 4K à un prix accessible, avec ray tracing et DLSS.",
    price: 799,
    imageUrl: "/assets/5000-gen/rtx-5070.jpg",
    inStock: false,
  },
  {
    id: 6,
    title: "NVIDIA RTX 5060 Ti",
    slug: "nvidia-rtx-5060-ti",
    description: "12 Go GDDR7 – Conçue pour un gaming 2K nouvelle génération fluide et détaillé.",
    price: 599,
    imageUrl: "/assets/5000-gen/rtx-5060-ti.jpg",
    inStock: false,
  },
  {
    id: 7,
    title: "NVIDIA RTX 5060",
    slug: "nvidia-rtx-5060",
    description: "12 Go GDDR7 – Gaming 1440p performant et abordable, idéal pour les joueurs exigeants.",
    price: 499,
    imageUrl: "/assets/5000-gen/rtx-5060.webp",
    inStock: false,
  },
  {
    id: 8,
    title: "NVIDIA RTX 4090",
    slug: "nvidia-rtx-4090",
    description: "24 Go GDDR6X – Performances extrêmes pour le gaming 8K, la création 3D et l’IA.",
    price: 1999,
    imageUrl: "/assets/4000-gen/rtx-4090.jpg",
    inStock: true,
  },
  {
    id: 9,
    title: "NVIDIA RTX 4080 SUPER",
    slug: "nvidia-rtx-4080-super",
    description: "16 Go GDDR6X – Gaming haut de gamme avec ray tracing avancé et DLSS 3.",
    price: 1399,
    imageUrl: "/assets/4000-gen/rtx-4080-super.webp",
    inStock: true,
  },
  {
    id: 10,
    title: "NVIDIA RTX 4080",
    slug: "nvidia-rtx-4080",
    description: "16 Go GDDR6X – Excellente carte 4K, équilibrant performance et efficacité énergétique.",
    price: 1299,
    imageUrl: "/assets/4000-gen/rtx-4080.jpg",
    inStock: false,
  },
  {
    id: 11,
    title: "NVIDIA RTX 4070 Ti SUPER",
    slug: "nvidia-rtx-4070-ti-super",
    description: "16 Go GDDR6X – Gaming ultra-fluide en 1440p et 4K léger, avec DLSS 3.",
    price: 999,
    imageUrl: "/assets/4000-gen/rtx-4070-ti-super.jpg",
    inStock: true,
  },
  {
    id: 12,
    title: "NVIDIA RTX 4070 Ti",
    slug: "nvidia-rtx-4070-ti",
    description: "12 Go GDDR6X – Parfaite pour le gaming 1440p haut de gamme et le streaming.",
    price: 899,
    imageUrl: "/assets/4000-gen/rtx-4070-ti.jpg",
    inStock: true,
  },
  {
    id: 13,
    title: "NVIDIA RTX 4070 SUPER",
    slug: "nvidia-rtx-4070-super",
    description: "12 Go GDDR6X – Excellent rapport performance/prix pour un gaming 1440p fluide.",
    price: 799,
    imageUrl: "/assets/4000-gen/rtx-4070-super.jpg",
    inStock: true,
  },
  {
    id: 14,
    title: "NVIDIA RTX 4070",
    slug: "nvidia-rtx-4070",
    description: "12 Go GDDR6X – Idéale pour un gaming 1440p avec consommation réduite.",
    price: 699,
    imageUrl: "/assets/4000-gen/rtx-4070.jpg",
    inStock: true,
  },
  {
    id: 15,
    title: "NVIDIA RTX 4060 Ti 16GB",
    slug: "nvidia-rtx-4060-ti-16g",
    description: "16 Go GDDR6 – Gaming 1440p avec textures haute résolution et fluidité optimale.",
    price: 599,
    imageUrl: "/assets/4000-gen/rtx-4060-ti-16g.jpg",
    inStock: true,
  },
  {
    id: 16,
    title: "NVIDIA RTX 4060 Ti",
    slug: "nvidia-rtx-4060-ti",
    description: "8 Go GDDR6 – Gaming performant en 1080p et 1440p avec DLSS 3.",
    price: 499,
    imageUrl: "/assets/4000-gen/rtx-4060-ti.jpg",
    inStock: true,
  },
  {
    id: 17,
    title: "NVIDIA RTX 4060",
    slug: "nvidia-rtx-4060",
    description: "8 Go GDDR6 – Carte idéale pour un gaming fluide en Full HD avec ray tracing.",
    price: 399,
    imageUrl: "/assets/4000-gen/rtx-4060.jpg",
    inStock: true,
  },
  {
    id: 18,
    title: "NVIDIA RTX 3090 Ti",
    slug: "nvidia-rtx-3090-ti",
    description: "24 Go GDDR6X – Ancienne référence ultime, idéale pour le 8K et la création.",
    price: 999,
    imageUrl: "/assets/3000-gen/rtx-3090-ti.jpg",
    inStock: true,
  },
  {
    id: 19,
    title: "NVIDIA RTX 3090",
    slug: "nvidia-rtx-3090",
    description: "24 Go GDDR6X – Parfaite pour créateurs et joueurs exigeants en 4K et 8K.",
    price: 899,
    imageUrl: "/assets/3000-gen/rtx-3090.jpg",
    inStock: true,
  },
  {
    id: 20,
    title: "NVIDIA RTX 3080 Ti",
    slug: "nvidia-rtx-3080-ti",
    description: "12 Go GDDR6X – Gaming premium en 4K avec ray tracing et DLSS.",
    price: 799,
    imageUrl: "/assets/3000-gen/rtx-3080-ti.jpg",
    inStock: true,
  },
  {
    id: 21,
    title: "NVIDIA RTX 3080",
    slug: "nvidia-rtx-3080",
    description: "10 Go GDDR6X – Gaming 4K fluide avec technologies RTX avancées.",
    price: 699,
    imageUrl: "/assets/3000-gen/rtx-3080.png",
    inStock: true,
  },
  {
    id: 22,
    title: "NVIDIA RTX 3070 Ti",
    slug: "nvidia-rtx-3070-ti",
    description: "8 Go GDDR6X – Idéale pour le 1440p ultra-fluide et le 4K léger.",
    price: 599,
    imageUrl: "/assets/3000-gen/rtx-3070-ti.jpg",
    inStock: true,
  },
  {
    id: 23,
    title: "NVIDIA RTX 3070",
    slug: "nvidia-rtx-3070",
    description: "8 Go GDDR6 – Gaming équilibré et polyvalent en 1440p.",
    price: 499,
    imageUrl: "/assets/3000-gen/rtx-3070.jpg",
    inStock: true,
  },
  {
    id: 24,
    title: "NVIDIA RTX 3060 Ti",
    slug: "nvidia-rtx-3060-ti",
    description: "8 Go GDDR6 – Parfaite pour un 1440p abordable et fluide.",
    price: 399,
    imageUrl: "/assets/3000-gen/rtx-3060-ti.jpg",
    inStock: true,
  },
  {
    id: 25,
    title: "NVIDIA RTX 3060",
    slug: "nvidia-rtx-3060",
    description: "12 Go GDDR6 – Gaming Full HD et 1440p accessible avec ray tracing.",
    price: 329,
    imageUrl: "/assets/3000-gen/rtx-3060.jpg",
    inStock: true,
  },
  {
    id: 26,
    title: "NVIDIA RTX 2080 Ti",
    slug: "nvidia-rtx-2080-ti",
    description: "11 Go GDDR6 – Haut de gamme Turing, encore excellent en 4K.",
    price: 499,
    imageUrl: "/assets/2000-gen/rtx-2080-ti.jpg",
    inStock: true,
  },
  {
    id: 27,
    title: "NVIDIA RTX 2080 SUPER",
    slug: "nvidia-rtx-2080-super",
    description: "8 Go GDDR6 – Version boostée pour un 1440p et 4K fluide.",
    price: 449,
    imageUrl: "/assets/2000-gen/rtx-2080-super.jpg",
    inStock: true,
  },
  {
    id: 28,
    title: "NVIDIA RTX 2080",
    slug: "nvidia-rtx-2080",
    description: "8 Go GDDR6 – Gaming haut de gamme, parfait pour 1440p et 4K léger.",
    price: 399,
    imageUrl: "/assets/2000-gen/rtx-2080.jpg",
    inStock: true,
  },
  {
    id: 29,
    title: "NVIDIA RTX 2070 SUPER",
    slug: "nvidia-rtx-2070-super",
    description: "8 Go GDDR6 – Excellente alternative pour du 1440p fluide.",
    price: 369,
    imageUrl: "/assets/2000-gen/rtx-2070-super.png",
    inStock: true,
  },
  {
    id: 30,
    title: "NVIDIA RTX 2070",
    slug: "nvidia-rtx-2070",
    description: "8 Go GDDR6 – Gaming QHD performant avec ray tracing.",
    price: 329,
    imageUrl: "/assets/2000-gen/rtx-2070.jpg",
    inStock: true,
  },
  {
    id: 31,
    title: "NVIDIA RTX 2060 SUPER",
    slug: "nvidia-rtx-2060-super",
    description: "8 Go GDDR6 – Performance solide en 1080p et 1440p.",
    price: 299,
    imageUrl: "/assets/2000-gen/rtx-2060-super.jpeg",
    inStock: true,
  },
  {
    id: 32,
    title: "NVIDIA RTX 2060",
    slug: "nvidia-rtx-2060",
    description: "6 Go GDDR6 – Accédez au ray tracing en Full HD.",
    price: 269,
    imageUrl: "/assets/2000-gen/rtx-2060.jpg",
    inStock: true,
  },
  {
    id: 33,
    title: "NVIDIA GTX 1080 Ti",
    slug: "nvidia-gtx-1080-ti",
    description: "11 Go GDDR5X – Haut de gamme Pascal, encore redoutable en 1440p et 4K.",
    price: 299,
    imageUrl: "/assets/1000-gen/gtx-1080-ti.png",
    inStock: true,
  },
  {
    id: 34,
    title: "NVIDIA GTX 1080",
    slug: "nvidia-gtx-1080",
    description: "8 Go GDDR5X – Excellente carte pour du 1440p fluide.",
    price: 249,
    imageUrl: "/assets/1000-gen/gtx-1080.jpg",
    inStock: true,
  },
  {
    id: 35,
    title: "NVIDIA GTX 1070 Ti",
    slug: "nvidia-gtx-1070-ti",
    description: "8 Go GDDR5 – Performances proches d’une 1080 pour un prix attractif.",
    price: 229,
    imageUrl: "/assets/1000-gen/gtx-1070-ti.jpg",
    inStock: true,
  },
  {
    id: 36,
    title: "NVIDIA GTX 1070",
    slug: "nvidia-gtx-1070",
    description: "8 Go GDDR5 – Gaming QHD fluide et confortable.",
    price: 199,
    imageUrl: "/assets/1000-gen/gtx-1070.webp",
    inStock: true,
  },
  {
    id: 37,
    title: "NVIDIA GTX 1060 6GB",
    slug: "nvidia-gtx-1060-6g",
    description: "6 Go GDDR5 – Full HD fluide avec bons réglages graphiques.",
    price: 149,
    imageUrl: "/assets/1000-gen/gtx-1060-6gb.jpg",
    inStock: true,
  },
  {
    id: 38,
    title: "NVIDIA GTX 1060 3GB",
    slug: "nvidia-gtx-1060-3g",
    description: "3 Go GDDR5 – Gaming 1080p léger et efficace.",
    price: 129,
    imageUrl: "/assets/1000-gen/gtx-1060-3gb.jpeg",
    inStock: true,
  },
  {
    id: 39,
    title: "NVIDIA GTX 1050 Ti",
    slug: "nvidia-gtx-1050-ti",
    description: "4 Go GDDR5 – Idéale pour eSports et jeux légers en Full HD.",
    price: 109,
    imageUrl: "/assets/1000-gen/gtx-1050-ti.jpg",
    inStock: true,
  },
  {
    id: 40,
    title: "NVIDIA GTX 1050",
    slug: "nvidia-gtx-1050",
    description: "2 Go GDDR5 – Carte d’entrée de gamme pour gaming occasionnel.",
    price: 89,
    imageUrl: "/assets/1000-gen/gtx-1050.webp",
    inStock: true,
  },
  {
    id: 41,
    title: "NVIDIA GTX 1030",
    slug: "nvidia-gtx-1030",
    description: "2 Go GDDR5 – Idéale pour multimédia, bureautique et petits jeux.",
    price: 69,
    imageUrl: "/assets/1000-gen/gtx-1030.jpg",
    inStock: true,
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const query = searchParams.get("query");

  let filteredProducts = products;

  if (query) {
    const searchTerm = query.toLowerCase();
    filteredProducts = products.filter(
      (product) =>
        product.title.toLowerCase().includes(searchTerm) ||
        product.description.toLowerCase().includes(searchTerm)
    );
  }

  return NextResponse.json(filteredProducts);
}